eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8084
spring:
  application:
    name: api-getway
zuul:
  routes:
    api-a:
       path: /tenant/**
       serviceId: tenant-service
    api-b:
       path: /quickpass/**
       serviceId: quick-pass

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000



